-- MySQL Script generated by MySQL Workbench
-- Tue Jun 23 23:56:37 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL,
  `foto_documento` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`catalogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`catalogo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `disponibilidade` TINYINT NOT NULL,
  PRIMARY KEY (`id`, `categoria_id`),
  INDEX `fk_catalogo_USUARIO_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_catalogo_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_catalogo_USUARIO`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_catalogo_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`troca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`troca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `livro_a` INT NOT NULL,
  `livro_b` INT NOT NULL,
  `dt_troca` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_troca_livro_a_idx` (`livro_a` ASC) VISIBLE,
  INDEX `fk_troca_livro_b_idx` (`livro_b` ASC) VISIBLE,
  CONSTRAINT `fk_troca_livro_a`
    FOREIGN KEY (`livro_a`)
    REFERENCES `mydb`.`catalogo` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_troca_livro_b`
    FOREIGN KEY (`livro_b`)
    REFERENCES `mydb`.`catalogo` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `livro` INT NOT NULL,
  `usuario_a` INT NOT NULL,
  `usuario_b` INT NOT NULL,
  `dt_doacao` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_livro_doacao_idx` (`livro` ASC) VISIBLE,
  INDEX `fk_doacao_usuario_a_idx` (`usuario_a` ASC) VISIBLE,
  INDEX `fk_doacao_usuario_b_idx` (`usuario_b` ASC) VISIBLE,
  CONSTRAINT `fk_livro_doacao`
    FOREIGN KEY (`livro`)
    REFERENCES `mydb`.`catalogo` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doacao_usuario_a`
    FOREIGN KEY (`usuario_a`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doacao_usuario_b`
    FOREIGN KEY (`usuario_b`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emprestimo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `livro` INT NOT NULL,
  `usuario_a` INT NOT NULL,
  `usuario_b` INT NOT NULL,
  `dt_emprestimo` DATE NOT NULL,
  `dt_devolucao` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_emprestimo_livro_idx` (`livro` ASC) VISIBLE,
  INDEX `fk_emprestimo_usuario_a_idx` (`usuario_a` ASC) VISIBLE,
  INDEX `fk_emprestimo_usuario_b_idx` (`usuario_b` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_livro`
    FOREIGN KEY (`livro`)
    REFERENCES `mydb`.`catalogo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_usuario_a`
    FOREIGN KEY (`usuario_a`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_usuario_b`
    FOREIGN KEY (`usuario_b`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `matricula` INT NOT NULL,
  `curso` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `departamento` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servidor` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `setor` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`terceirizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`terceirizado` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `empresa` INT NOT NULL,
  `matricula_empresa` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acao` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historico_catalogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historico_catalogo` (
  `ts_acao` TIMESTAMP NOT NULL,
  `livro` INT NOT NULL,
  `acao` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `id_livro` INT NOT NULL,
  `nome_proprietario` VARCHAR(100) NOT NULL,
  `id_proprietario` INT NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `disponiblidade` TINYINT NOT NULL,
  PRIMARY KEY (`ts_acao`, `livro`, `acao`),
  INDEX `fk_acao_idx` (`acao` ASC) VISIBLE,
  CONSTRAINT `fk_acao`
    FOREIGN KEY (`acao`)
    REFERENCES `mydb`.`acao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
